### ISSUE TITLE
Trouble with connecting any client

### ISSUE THREAD

**Issue by camielschoonens** [akirk/enable-mastodon-apps#28]
Hi, I’ve tried to connect to my WordPress website using multiple clients (Ivory, ELK, IceCubes). Only IceCubes is able to connect but does behave buggy (e.g. doesn’t refresh posts, avatars get mixed up).

I did some debugging this morning through the logging function when connecting.

With **Ivory** I get the following result at this api endpoint when trying to connect the app: https://schoonens.nl/api/v1/apps?_wpnonce=1bb4308bdb&_pretty=1

‘{
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method.",
    "data": {
        "status": 404
    }
}’

When going through the logs for **IceCubes** I get the following empty result when refreshing the home timeline through this api endpoint: https://schoonens.nl/api/v1/timelines/home?_wpnonce=1bb4308bdb&_pretty=1

‘[]’

The website is a vanilla WordPress install for testing purposes, I have five plugins activated:
- ActivityPub
- Akismet Anti-Spam: Spam Protection
- Enable Mastodon Apps
- Friends
- Webmention

**Comment by akirk** [comment]
Sorry about the trouble, the 404 error for the apps endpoint is misleading, it is only a [HTTP POST endpoint](https://github.com/akirk/enable-mastodon-apps/blob/main/includes/class-mastodon-api.php#L150) and your browser sends a GET request.

If you can see the client in the list of apps, the endpoint worked.

The empty timeline could be due to post formats. I suppose you have subscribed to feeds/Mastodon accounts and can see the posts on your blog at /friends/? On the Enable Mastodon Apps settings page, each app has a post format selector, if you tune that depending on your needs the timeline should have entries. The reason for this configuration option is that you can use a Pixelfed client for image type posts, and a Mastodon one for status posts.

Does this help you?

Regarding the Ivory connection issue, this is currently broken on macos but it should work on iOS. I've yet been unsuccessful to find out what Ivory doesn't like.

**Comment by camielschoonens** [comment]
Hi, thanks for the quick reply and the hint to the post formats. I didn’t see that the field was a selector field with the options to select multiple post formats. In the end that solved the problem of nothing showing up in the Icecubes timeline.

On topic of Ivory, for me it’s not working on the MacOS and not on the iOS versions. If you want I can connect to your instance to create a log on your server.

**Comment by akirk** [comment]
I released version [0.4.0](https://github.com/akirk/enable-mastodon-apps/releases/tag/0.4.0) today, could you try again with that version? Thanks!

**Comment by camielschoonens** [comment]
I updated early this morning and the behavior in the Ice Cubes client is much better. E.g. profile pictures are now loading for the user accounts where previously every account was showing my profile picture.

The iOS Ivory client still doesn’t connect. If you want I can post the logs later today. Will do some further debugging myself too with other clients.

**Comment by akirk** [comment]
Thank you for testing again, this is good to hear! I discovered #32 (wrong people attributed for boosting) after the release, I'm looking into fixing that as well.

Ivory iOS logs would be interesting, thank you!

**Comment by camielschoonens** [comment]
Hi Alex,

I would come back on this topic. I checked again with 2 other iOS clients: Ivory and Mona. Both have trouble connecting and I fail to understand why.

When connecting with either app I get the following response through the API in the debugger you provide in the plugin.

{
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method.",
    "data": {
        "status": 404
    }
}

The following is also logged, in this case for Mona.

Debugger [2023-07-28 10:25:23.897] 200 POST [/api/v1/apps](https://schoonens.nl/api/v1/apps?_wpnonce=d330fffc7f&_pretty=1)
params array (
  'redirect_uris' => 'com.jonny.mona://oauth',
  'scopes' => 'read write push follow',
  'client_name' => 'Mona for iPhone',
  'website' => 'https://mastodon.social/@MonaApp',
)
current_user 0
user_agent 'Mastodon/410 CFNetwork/1408.0.4 Darwin/20.1.0'
app Enable_Mastodon_Apps\Mastodon_App::__set_state(array(
   'term' => 
  WP_Term::__set_state(array(
     'term_id' => 177,
     'name' => 'enable-mastodon-apps',
     'slug' => 'enable-mastodon-apps',
     'term_group' => 0,
     'term_taxonomy_id' => 177,
     'taxonomy' => 'mastodon-app',
     'description' => '',
     'parent' => 0,
     'count' => 0,
     'filter' => 'raw',
     'meta' => 
    array (
    ),
  )),
))

I’m failing to figure out if this has to do with my setup or with the plugin. Have you yourself been able to get this to work with Ivory or Mona for iOS?

**Comment by camielschoonens** [comment]
Hi Alex,

I've been playing around with the plugin and several clients a bit more. I think there is an issue with my webhosts which is causing the login issues through several apps. My reasoning, I've setup a local environment where I could connect with Ivory iOS and Ice Cubes without issues.

The exact same environment on my hosting provider works only for Ice Cubes but not for any other client. E.g. Ivory says there is a 'permision issue' when it's supposed to redirect to the login page and for instance ELK gives a plain error saying it can't connect at all.

This is the most recent log that I got from ELK, not sure if there is any more logging or debugging I can do for you at this moment.

Debugger [2023-08-03 14:08:59.996] 200 POST [/api/v1/apps](https://schoonens.blog/api/v1/apps?_wpnonce=235873c885&_pretty=1)
params array (
  'client_name' => 'Elk',
  'website' => 'https://elk.zone',
  'redirect_uris' => 'https://elk.zone/api/schoonens.blog/oauth/https%3A%2F%2Felk.zone',
  'scopes' => 'read write follow push',
)
json array (
  'client_name' => 'Elk',
  'website' => 'https://elk.zone',
  'redirect_uris' => 'https://elk.zone/api/schoonens.blog/oauth/https%3A%2F%2Felk.zone',
  'scopes' => 'read write follow push',
)
current_user 0
user_agent 'undici'
app Enable_Mastodon_Apps\Mastodon_App::__set_state(array(
   'term' => 
  WP_Term::__set_state(array(
     'term_id' => 142,
     'name' => 'enable-mastodon-apps',
     'slug' => 'enable-mastodon-apps',
     'term_group' => 0,
     'term_taxonomy_id' => 142,
     'taxonomy' => 'mastodon-app',
     'description' => '',
     'parent' => 0,
     'count' => 0,
     'filter' => 'raw',
     'meta' => 
    array (
    ),
  )),
))
