### ISSUE TITLE
Critical Error on Saving Changes, Part 2

### ISSUE THREAD

**Issue by electricbrick** [akirk/enable-mastodon-apps#7]
After enabling the app, I attempted to log in via Ice Cubes and then Ivory, to no avail. I checked the plugin settings page, clicked the 'Save' button and encountered the following error:

`Error Details
=============
An error of type E_ERROR was caused in line 406 of the file /nas/content/live/mysiteurl/wp-content/plugins/enable-mastodon-apps-main/includes/class-mastodon-admin.php. Error message: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /nas/content/live/mysiteurl/wp-content/plugins/enable-mastodon-apps-main/includes/class-mastodon-admin.php:406
Stack trace:
#0 /nas/content/live/mysiteurl/wp-content/plugins/enable-mastodon-apps-main/includes/class-mastodon-admin.php(406): implode('', '')
#1 /nas/content/live/mysiteurl/wp-includes/class-wp-hook.php(308): Enable_Mastodon_Apps\Mastodon_Admin->admin_page('')
#2 /nas/content/live/mysiteurl/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 /nas/content/live/mysiteurl/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /nas/content/live/mysiteurl/wp-admin/admin.php(259): do_action('settings_page_e...')
#5 /nas/content/live/mysiteurl/wp-admin/options-general.php(10): require_once('/nas/content/li...')
#6 {main}
  thrown`

**Comment by knut-hildebrandt** [comment]
For me this was fixed with version 0.2

**Comment by electricbrick** [comment]
@knut-hildebrandt this was in version 0.2 – sorry I should have specified that for @akirk – good looking out

**Comment by electricbrick** [comment]
The 2.1 update has resolved the issue above.

**Comment by akirk** [comment]
Does it work with Ivory? I haven't yet managed to get Icecubes to  work

**Comment by electricbrick** [comment]
So the error message went away, and I want able to see my server with Ice Cubes. But authentication with every iOS app I have (Mastodon official, Ivory, and Ice Cubes) all still fail.


**Ice Cubes:**
![image](https://user-images.githubusercontent.com/2481417/232256093-07620f98-4c64-4670-8a44-939d7b64c7f5.png)

![image](https://user-images.githubusercontent.com/2481417/232256107-200ec803-65f8-4aee-98da-ebd1527ecc13.png)

After this stage it just asks me to authenticate but nothing happens on the app side:

![image](https://user-images.githubusercontent.com/2481417/232256148-7bcba4a4-8ecb-428b-9153-b84499108ee6.jpeg)

**Ivory**

![image](https://user-images.githubusercontent.com/2481417/232256157-2dd4c6fd-6e71-4d75-8596-0f79506a33c2.png)

**Mastodon**

![image](https://user-images.githubusercontent.com/2481417/232256165-2443b9d5-e3f4-496a-89d9-9e4d6b030c8f.png)

![image](https://user-images.githubusercontent.com/2481417/232256171-ef0e773d-8063-4cfc-8539-2e806bd7e0d3.png)

**Comment by akirk** [comment]
Thanks, @electricbrick for testing! I just pushed some more fixes that make Icecubes load more me. Since you already tried 0.2.1 without me releasing it to the plugin directory, you might be able to test these latest changes again without me making a new release? The version is still 0.2.1 but the latest commit is 00d1e684932586acf032c25e4cbcfeabb490f5ac. Thanks!

**Comment by electricbrick** [comment]
@akirk I pushed the update but am still seeing the sort of recursive authorize look where nothing happens in Ice Cubes (my expectation would be some sort of "success!" or confirmation screen after pressing the "Authorize" button on my WordPress-based login screen. I'm in a bit of a rush so all I can provide is a screenshot of my EMA dashboard. It's definitely creating tokens but seems like the "handshake" isn't being completed. Maybe I should pull my error logs later?

![Screenshot 2023-04-16 at 13-46-09 Mastodon Apps ‹ Tom Finley — WordPress](https://user-images.githubusercontent.com/2481417/232331744-bc991522-2542-4f9b-ad09-bac67ef6ff56.png)

**Comment by akirk** [comment]
Thank you, ther errors are just about the admin page, I fixed that bug in 0a333a2d1ace7ffe01229aa08625811d04f70c26.

The Swift apps are really picky about the correct JSON response format, I had to run Icecubes locally and add some debug code to find out what's wrong.

So, the bug above is about the redirect_uri(s) handling which I got slightly wrong and hope that I have fixed now (Mastodon seems a bit peculiar in that it allows multiple uris).

But the reason the apps are not booting is that they are not happy with the response from the server and are (from what I experienced so far) not very chatty about what it exactly is they don't like. So I am trying to fill the holes (that I can discover) until they are happy.

I have done another iteration of fixes, maybe this makes it work for you? Thanks for checking again and again!

**Comment by electricbrick** [comment]
@akirk my pleasure — it's you we should be thanking for taking this on. When it's all working it will be quite an achievement. Soooo many thanks.

The last update didn't change any results for me. Mastodon proper, Mammoth, Ice Cubes, and Ivory all still refuse to authenticate.

![image](https://user-images.githubusercontent.com/2481417/232373771-8bac2a3f-1dd4-4283-841b-7a29b793b97e.png)

**Comment by electricbrick** [comment]
@akirk I disabled the following IndieWeb plugins and have successfully authenticated Ice Cubes to my site-hosted Mastodon account.

![Screenshot 2023-04-17 at 14-24-48 Plugins ‹ Tom Finley — WordPress](https://user-images.githubusercontent.com/2481417/232578672-e5f009af-9980-424b-a921-e6c8f3f5bc03.png)
